import React, { Component } from 'react'
import style from './CSS/aboutUs.module.css'

export default class Text extends Component {
    render() {
        return (
            <div className="col-lg-12 col-md-12 col-sm-12">

                    <p id={style.title}> Our Story </p>
                    <p id={style.text}>Nulla tincidunt nulla id convallis fringilla. Integer ut lobortis mauris. Aliquam erat volutpat. Donec sed magna quis turpis sagittis malesuada. Phasellus posuere velit vel turpis tempus feugiat. Ut a finibus tortor. Mauris velit nisl, fringilla ut dolor in, efficitur faucibus neque. Pellentesque tempor non dui eu sodales. Sed gravida purus augue, et suscipit eros volutpat sed. Integer varius dui ac nisi faucibus, nec tempor tellus sollicitudin. Nunc tincidunt enim nibh. Sed hendrerit tortor eget elit aliquet consequat. Curabitur ultrices laoreet odio et pharetra. Pellentesque eu tortor consequat, iaculis dui eu, malesuada risus. Nam interdum id massa nec ultrices. Vestibulum at ipsum sapien. Aenean sit amet nunc in eros molestie egestas non id turpis. Phasellus a egestas magna. Integer id lobortis orci, in mollis nibh. Pellentesque vulputate eu ex et vestibulum. Nullam elit odio, fermentum sit amet dui convallis, malesuada pellentesque elit. Vestibulum sodales sit amet ligula non ultrices. Aliquam volutpat odio vel tincidunt congue. In hac habitasse platea dictumst. Sed sit amet nulla eget libero iaculis varius nec in felis. Aenean sit amet augue ut erat ultrices rhoncus. Etiam dapibus varius augue, non malesuada neque rhoncus ac. Cras lobortis feugiat sem non pellentesque. Praesent vel sagittis nisi. Maecenas sapien tortor, ullamcorper nec posuere vel, sodales in nunc. Fusce dolor tellus, sodales auctor tellus id, accumsan sagittis tellus. Maecenas ut interdum erat, at hendrerit nunc. Pellentesque faucibus sagittis massa sed blandit. Nulla id accumsan augue, vel molestie augue. Duis at mi turpis. Duis pretium suscipit nisl, vel viverra risus pulvinar sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a tempus felis. Praesent libero mi, facilisis ut pulvinar sit amet, pellentesque et massa. Integer at justo orci. Fusce in malesuada neque. Etiam dui felis, mollis eget lobortis nec, efficitur non quam. Nulla congue eros nisi, in fringilla massa efficitur id. Maecenas dictum, lectus sed dignissim viverra, enim tellus pellentesque sem, nec semper dolor justo at nibh. Proin leo dolor, commodo sed vestibulum quis, ultrices finibus mauris. Cras lobortis nibh sem, non euismod purus luctus eget. Mauris vehicula sed felis vel lacinia. Sed dictum, ipsum non viverra dapibus, quam justo dignissim urna, in tincidunt risus risus non tellus. Praesent nec lacinia orci, in ultrices ipsum. Maecenas ultrices augue nibh, mollis dignissim sem gravida eu. Pellentesque interdum elementum dapibus. Suspendisse ultrices, ligula in rutrum tincidunt, odio ante gravida magna, nec suscipit nunc magna a nibh. Morbi venenatis sit amet neque at ultrices.
                    <br></br>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmodtempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        )
    }
}